parameters:
    ezsystems.tweetbundle.twitter.client.class: EzSystems\TweetFieldTypeBundle\Twitter\TwitterClient

services:
    ezsystems.tweetbundle.twitter.client:
        class: %ezsystems.tweetbundle.twitter.client.class%
